In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.impute import SimpleImputer

In [ ]:
data = pd.read_csv('data/all_games.csv')

In [14]:
data.head(n=10)

,name,platform,release_date,summary,meta_score,user_review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",99,9.1
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,98,7.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",98,8.4
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9
5,Super Mario Galaxy,Wii,"November 12, 2007",[Metacritic's 2007 Wii Game of the Year] The u...,97,9.1
6,Super Mario Galaxy 2,Wii,"May 23, 2010","Super Mario Galaxy 2, the sequel to the galaxy...",97,9.1
7,Red Dead Redemption 2,Xbox One,"October 26, 2018",Developed by the creators of Grand Theft Auto ...,97,8.0
8,Grand Theft Auto V,Xbox One,"November 18, 2014",Grand Theft Auto 5 melds storytelling and game...,97,7.9
9,Grand Theft Auto V,PlayStation 3,"September 17, 2013","Los Santos is a vast, sun-soaked metropolis fu...",97,8.3

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18800 entries, 0 to 18799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          18800 non-null  object
 1   platform      18800 non-null  object
 2   release_date  18800 non-null  object
 3   summary       18686 non-null  object
 4   meta_score    18800 non-null  int64
 5   user_review   18800 non-null  object
dtypes: int64(1), object(5)
memory usage: 881.4+ KB

In [16]:
#tamano del dataset 
data.shape

(18800, 6)

In [17]:
#valores duplicados
data.duplicated().sum()
# eliminacion datos duplicados
data.drop_duplicates(inplace=True)

In [18]:
# valores nulos
data.isnull().sum()

name              0
platform          0
release_date      0
summary         114
meta_score        0
user_review       0
dtype: int64

In [19]:
# porcentaje de nulos
data.isnull().sum()/data.shape[0]*100

name            0.000000
platform        0.000000
release_date    0.000000
summary         0.606383
meta_score      0.000000
user_review     0.000000
dtype: float64

In [20]:
# seleccion de valores NaN
data[data.isnull().any(axis=1)]

,name,platform,release_date,summary,meta_score,user_review
833,Injustice 2: Legendary Edition,PlayStation 4,"March 27, 2018",NaN,88,7.6
1472,Moto Racer Advance,Game Boy Advance,"December 5, 2002",NaN,86,tbd
1535,Mini Metro,Switch,"August 30, 2018",NaN,86,8.4
1649,Out of the Park Baseball 13,PC,"April 9, 2012",NaN,85,7.8
2427,Guild Wars 2: Path of Fire,PC,"September 22, 2017",NaN,83,7.3
...,...,...,...,...,...,...
17999,One Piece: Unlimited Cruise SP,PlayStation 4,"February 10, 2012",NaN,46,7.0
18134,AeternoBlade II,Wii U,"October 11, 2019",NaN,44,4.4
18253,Surgeon Simulator: Experience Reality,PlayStation 4,"December 3, 2016",NaN,43,4.3
18532,The Ripping Friends,Game Boy Advance,"March 24, 2002",NaN,38,tbd
18717,Smash 'N' Survive,PlayStation 3,"February 22, 2012",NaN,31,tbd

In [21]:
# remplzar valores nulos
data.fillna('summary not available',inplace=True)

In [22]:
# validar valores nulos
data.isna().sum()

name            0
platform        0
release_date    0
summary         0
meta_score      0
user_review     0
dtype: int64

In [30]:
data.describe()

         meta_score
count  18800.000000
mean      70.648883
std       12.225006
min       20.000000
25%       64.000000
50%       72.000000
75%       80.000000
max       99.000000

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18800 entries, 0 to 18799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          18800 non-null  object
 1   platform      18800 non-null  object
 2   release_date  18800 non-null  object
 3   summary       18800 non-null  object
 4   meta_score    18800 non-null  int64
 5   user_review   18800 non-null  object
dtypes: int64(1), object(5)
memory usage: 881.4+ KB

In [ ]:
# columnas categoricas
data.select_dtypes(include=['object'])
data.select_dtypes(include=['object']).head()
data.select_dtypes(include=['object']).columns

Index(['name', 'platform', 'release_date', 'summary', 'user_review'], dtype='object')

In [38]:
data.select_dtypes(include=['object']).head()

,name,platform,release_date,summary,user_review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,"November 23, 1998","As a young boy, Link is tricked by Ganondorf, ...",9.1
1,Tony Hawk's Pro Skater 2,PlayStation,"September 20, 2000",As most major publishers' development efforts ...,7.4
2,Grand Theft Auto IV,PlayStation 3,"April 29, 2008",[Metacritic's 2008 PS3 Game of the Year; Also ...,7.7
3,SoulCalibur,Dreamcast,"September 8, 1999","This is a tale of souls and swords, transcendi...",8.4
4,Grand Theft Auto IV,Xbox 360,"April 29, 2008",[Metacritic's 2008 Xbox 360 Game of the Year; ...,7.9

In [34]:
data.describe(include='object')

         name platform       release_date                summary user_review
count   18800    18800              18800                  18800       18800
unique  12254       22               4533                  14648          94
top      Cars       PC  November 14, 2006  summary not available         tbd
freq        9     4864                 48                    114        1365

In [39]:
# valores no numericos en la columna user_review
non_numeric_values = data[pd.to_numeric(data['user_review'], errors='coerce').isna()]
print(non_numeric_values['user_review'])

679      tbd
963      tbd
1277     tbd
1472     tbd
2098     tbd
        ...
18594    tbd
18639    tbd
18700    tbd
18715    tbd
18717    tbd
Name: user_review, Length: 1365, dtype: object

In [40]:
# comvertir los valores de la columna user_review a numericos
data['user_review'] = pd.to_numeric(data['user_review'], errors='coerce')

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18800 entries, 0 to 18799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          18800 non-null  object
 1   platform      18800 non-null  object
 2   release_date  18800 non-null  object
 3   summary       18800 non-null  object
 4   meta_score    18800 non-null  int64
 5   user_review   17435 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 881.4+ KB

In [43]:
data['user_review'].count()

17435

In [44]:
difference = 18800 - data['user_review'].count()
print(difference)

1365